Feature/teaser adjustments
aakb/genlydaarhus pull request #19
Opened 2017-03-21 10:18 UTC by tuj

Added price to activity and teaser.

2017-03-21 12:12 UTC, cableman requested changes

2017-03-21 12:12 UTC, cableman commented on web/themes/custom/genlyd_aarhus/genlyd_aarhus.theme
> +
Two new lines?

2017-03-21 12:12 UTC, cableman commented on web/themes/custom/genlyd_aarhus/genlyd_aarhus.theme
> +  $price = $node->field_price->value;
Another way could be this, but it's more a personal taste....

```
$priceRaw = $node->field_price->value;
$price = \Drupal::translation()->translate('Free');
if (isset($priceRaw) || $priceRaw > 0) {
   $price = \Drupal::translation()->translate(':price kr.', [ ':price' => $priceRaw ]);
}
```

2017-03-21 12:12 UTC, cableman commented on web/themes/custom/genlyd_aarhus/genlyd_aarhus.theme
> +  // Set price text.
This is the same code as above in "genlyd_aarhus_preprocess_node__activity" and it's in the same file, so maybe a helper function ?

2017-03-21 12:32 UTC, cableman approved these changes

2017-03-21 12:32 UTC, merged

2017-03-23 09:03 UTC, tuj commented on web/themes/custom/genlyd_aarhus/genlyd_aarhus.theme
> +  $price = $node->field_price->value;
Changed to private function