Issue #GEN-186: Added fixes to flow
aakb/genlydaarhus pull request #26
Opened 2017-03-28 12:55 UTC by tuj

* Make progress bar clickable

2017-03-28 13:30 UTC, cableman requested changes

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormAbout.php
> +    $this->acceptStep(1);
What is acceptStep 1 ?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormBase.php
> +   * Accept a step in the form.
What do it mean to accept a step in the form?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormCategories.php
> +    $progressBar['items'][2]['active'] = TRUE;
Could the "2" here have been a name - categories?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormConfirm.php
> +    $progressBar['items'][5]['active'] = TRUE;
Could 5 have been a name?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormDetails.php
> +    $progressBar['items'][4]['active'] = TRUE;
Could 4 have been a name?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormImage.php
> +    // Set progress bar data.
This seam to be the same 3 lines of code only the number change... shoul it have been in an setFromProgress() function.

Could 3 have been a name?

2017-03-28 13:30 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormInformation.php
> +    $progressBar['items'][1]['active'] = TRUE;
Could 1 have been a name?

2017-03-28 13:30 UTC, cableman commented on web/themes/custom/genlyd_aarhus/source/_patterns/01-modules/progress-bar.twig
>  <div class="progress-bar">
Missing @file documentation.

And missing available vars: loop? item?

2017-03-28 17:00 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/01-modules/progress-bar.twig
>  <div class="progress-bar">
We do not have @file descriptions on the pattern lab twig files atm

2017-03-29 06:33 UTC, tuj commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormBase.php
> +   * Accept a step in the form.
Added extra comment

2017-03-29 06:34 UTC, tuj commented
Ping for re-review

2017-03-29 07:25 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormBase.php
> +   * Accept a step in the form.
So what is this: https://github.com/aakb/genlydaarhus/blob/develop/web/themes/custom/genlyd_aarhus/templates/misc/status-messages.html.twig

2017-03-29 07:26 UTC, cableman commented on web/themes/custom/genlyd_aarhus/source/_patterns/01-modules/progress-bar.twig
>  <div class="progress-bar">
So what is this: https://github.com/aakb/genlydaarhus/blob/develop/web/themes/custom/genlyd_aarhus/templates/misc/status-messages.html.twig

2017-03-29 07:27 UTC, cableman commented on web/modules/custom/itk_activity/src/Form/Multistep/MultistepFormBase.php
> +    // @TODO: Validate data
Should it be validated?

2017-03-29 07:44 UTC, cableman approved these changes

2017-03-29 07:44 UTC, merged