Feature/actvity contact
aakb/genlydaarhus pull request #39
Opened 2017-04-04 11:45 UTC by tuj

Added contact form to activity page

2017-04-05 08:35 UTC, magnify reviewed
Assigning to @cableman for review.

2017-04-05 08:35 UTC, magnify commented on CHANGELOG.md
>  * Enabled Metatag: Open Graph module and added tags
Missing punctuation?

2017-04-18 13:02 UTC, magnify requested changes
@mikkelboesen we should consider getting @cableman to take a look at this too.

2017-04-18 13:02 UTC, magnify commented on config/sync/user.role.anonymous.yml
> -  - 'view sp metadata'
Should this be removed?

2017-04-18 13:02 UTC, magnify commented on web/modules/custom/itk_activity/itk_activity.info.yml
> +core: 8.x
Missing new line.

2017-04-18 13:02 UTC, magnify commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/activity-sidebar.twig
> +{# @TODO: Refactor #}
Do we want this @TODO here?

2017-04-18 14:01 UTC, tuj commented on web/modules/custom/itk_activity/itk_activity.info.yml
> +core: 8.x
Not missing

2017-04-18 14:01 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/activity-sidebar.twig
> +{# @TODO: Refactor #}
Fixed

2017-04-18 14:01 UTC, tuj commented on config/sync/user.role.anonymous.yml
> -  - 'view sp metadata'
Fixed

2017-04-18 14:24 UTC, magnify approved these changes

2017-04-18 14:24 UTC, merged