Feature/add activity
aakb/genlydaarhus pull request #8
Opened 2017-03-09 11:02 UTC by magnify

2017-03-09 14:05 UTC, tuj requested changes

2017-03-09 14:05 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/00-elements/forms/fieldset.scss
> +  magin: 0;
magin?

2017-03-09 14:05 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/00-elements/forms/radio.twig
> +    <div class="radio--label">{{ radio.label }}</div>
Wierd space?

2017-03-09 14:05 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/01-modules/section-text-with-icon.twig
> +        {% include iconName ? "@elements/icons/icon-" ~ iconName ~ ".twig" : "@elements/icons/icon-arrow-dark-green-small.twig" %}
Perhaps default should be en empty icon?

2017-03-09 14:05 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/add-activity.twig
> +
Buttons in pattern-lab?

2017-03-09 14:05 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/add-activity.twig
> +  {{ form.form_build_id }}
{% if form %}

2017-03-09 14:06 UTC, magnify commented on web/themes/custom/genlyd_aarhus/source/_patterns/00-elements/forms/fieldset.scss
> +  magin: 0;
Whoa!

2017-03-09 14:06 UTC, magnify commented on web/themes/custom/genlyd_aarhus/source/_patterns/00-elements/forms/fieldset.scss
> +  magin: 0;
magin is the new margin.

2017-03-09 14:34 UTC, magnify commented on web/themes/custom/genlyd_aarhus/source/_patterns/01-modules/section-text-with-icon.twig
> +        {% include iconName ? "@elements/icons/icon-" ~ iconName ~ ".twig" : "@elements/icons/icon-arrow-dark-green-small.twig" %}
Let's stick with this for now. We will probably get back to it.

2017-03-09 14:35 UTC, magnify commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/add-activity.twig
> +
Waiting for merge with 5 step form code, after merge I will take a look at getting it to work in Pattern Lab.

2017-03-09 14:37 UTC, magnify commented
Commit changes, please review.

2017-03-10 07:33 UTC, tuj commented on web/themes/custom/genlyd_aarhus/source/_patterns/02-components/add-activity.twig
> +
Ok

2017-03-10 07:33 UTC, merged